### PR TITLE
chore: Bump OAV version to 0.19.0

### PR DESCRIPTION
**Pull request by nschonni**

### CODE REVIEW

**Comment by nschonni** [comment]
@sergey-shandar @NullMDR does this make sense to get in the latest OAV improvements?

**Comment by sergey-shandar** [comment]
@nschonni  please, bump `package.json` version as well.

**Comment by nschonni** [comment]
@sergey-shandar that's what this PR is doing, or do you mean to the latest sub-patch version?

**Comment by sergey-shandar** [comment]
@nschonni I mean, a version of `@azure/rest-api-specs-scripts`.

**Comment by nschonni** [comment]
Thanks, I bumped it to 0.4.2. If you prefer it as a 0.5, let me know

**Pull request merged**
